name: Merge Dev into Main

on:
  schedule:
    - cron: '0 0 * * *' # Executar todos os dias à meia-noite (UTC)

jobs:
  merge_dev_into_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Versão do Node.js

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
        continue-on-error: true

      - name: Build
        run: npm run build
        continue-on-error: true

      - name: Merge dev into main
        if: ${{ success() }}
        run: |
          git checkout main
          git merge dev --no-ff --no-edit
          git push origin main
